### ISSUE TITLE
Practica 3. Graficaciòn de funciones con Sphero

### ISSUE THREAD

**Issue by A-Lorely-Z** [SistemasTecTlaxiaco/practica-6-relaciones-funciones-y-plano-cartesiano-lennin-s-team-1as#1]
[FUNCIONES EN UN PLANO CARTESIANO CON SPHERO.pdf](https://github.com/user-attachments/files/17142863/FUNCIONES.EN.UN.PLANO.CARTESIANO.CON.SPHERO.pdf)

**Comment by Johnc-byte** [comment]
Portada 25/25
Procedimiento 25/25
Figuras, ilustraciones y fotografías. 25/25
Resultados y conclusiones 25/25
Calificación: 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
